### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by rcj60560** [zhibuyu/Flutter_Stocks#2]
方便加个微信吗 
刚开始学dart @zhibuyu

**Comment by zhibuyu** [comment]
可以，我也是去年只看了一段时间，最近再看其他方面的知识。微信号：naruto-yu-X

**Comment by zhibuyu** [comment]
我看的是慕课网的Flutter开发第一步-Dart编程语言入门http://www.imooc.com/learn/1035和Flutter中文网的文档，其他有问题就是百度谷歌查的，你可以参考下
