### ISSUE TITLE
老大，请求更新到最新版本的flutter和支持AndroidX

### ISSUE THREAD

**Issue by superadmini** [zhibuyu/Flutter_Stocks#4]
老大，请求更新到最新版本的flutter和支持AndroidX

**Comment by superadmini** [comment]
The named parameter 'bgcolor' isn't defined.
Try correcting the name to an existing named parameter, or defining a new parameter with this name.

**Comment by zhibuyu** [comment]
已做兼容更新

**Comment by superadmini** [comment]
非常感谢。
